#ifndef __UMS_REQUEST_H__
#define __UMS_REQUEST_H__

#define UMS_REQUEST_ENTER_UMS_SCHEDULING 1

#define UMS_REQUEST_EXIT_UMS_SCHEDULING 2

#define UMS_REQUEST_REGISTER_SCHEDULER_THREAD 3

#define UMS_REQUEST_NEW_COMPLETION_LIST 4

#define UMS_REQUEST_REGISTER_COMPLETION_ELEM 5

#define UMS_REQUEST_REMOVE_COMPLETION_LIST 6

#define UMS_REQUEST_REMOVE_COMPLETION_ELEM 7

#define UMS_REQUEST_WAIT_UMS_SCHEDULER 8

#define UMS_REQUEST_YIELD 9

#define UMS_REQUEST_EXEC 10

#define UMS_REQUEST_DEQUEUE_COMPLETION_LIST 11

#endif /* __UMS_REQUEST_H__ */
