#ifndef __UMS_REQUEST_H__
#define __UMS_REQUEST_H__

#include "../module/ums_scheduler.h"
#define UMS_REQUEST_ENTER_UMS_SCHEDULING 16

#define UMS_REQUEST_EXIT_UMS_SCHEDULING 32

#define UMS_REQUEST_REGISTER_SCHEDULER_THREAD 64

#define UMS_REQUEST_NEW_COMPLETION_LIST 128

#define UMS_REQUEST_REGISTER_COMPLETION_ELEM 256

#define UMS_REQUEST_REMOVE_COMPLETION_LIST 512

#define UMS_REQUEST_REMOVE_COMPLETION_ELEM 1024

#define UMS_REQUEST_REGISTER_ENTRY_POINT 2048

#define UMS_REQUEST_WAIT_UMS_SCHEDULER 4096

#define UMS_REQUEST_YIELD 8192

#define UMS_REQUEST_EXEC 16384

#define UMS_REQUEST_DEQUEUE_COMPLETION_LIST 32768
#endif /* __UMS_REQUEST_H__ */
