#ifndef __UMS_REQUEST_H__
#define __UMS_REQUEST_H__

#define UMS_REQUEST_ENTER_UMS_SCHEDULING 0

#define UMS_REQUEST_REGISTER_SCHEDULER_THREAD 1

#define UMS_REQUEST_NEW_COMPLETION_LIST 2

#define UMS_REQUEST_REGISTER_COMPLETION_ELEM 3


#endif /* __UMS_REQUEST_H__ */
